"""Стандартные размеры и отступы для виджетов."""

# Базовые отступы и высота строки
PADDING = 10
LINE_HEIGHT = 30

# Размеры фреймов
INPUT_FRAME_WIDTH = 750
INPUT_FRAME_HEIGHT = 160
SAVE_FRAME_WIDTH = 600
SAVE_FRAME_HEIGHT = 100
CURVES_FRAME_WIDTH = 1500
CURVES_FRAME_HEIGHT = 200

# Ширины виджетов
ENTRY_WIDTH = 300
COMBO_WIDTH = 200
SMALL_COMBO_WIDTH = 150
SIZE_COMBO_WIDTH = 100
FORMAT_COMBO_WIDTH = 80
PATH_ENTRY_WIDTH = 600
RANGE_ENTRY_WIDTH = 80
OFFSET_ENTRY_WIDTH = 40
PREVIEW_WIDTH = 640
PREVIEW_HEIGHT = 480
EDITOR_HEIGHT = 180

# Горизонтальные позиции и смещения
AXIS_COMBO_X = 200
AXIS_ENTRY_X = 450
LABEL_SIZE_OFFSET = 225
SIZE_COMBO_OFFSET = 400
AXIS_LABEL_SIZE_X = AXIS_COMBO_X + LABEL_SIZE_OFFSET
AXIS_UNIT_X = AXIS_COMBO_X + SIZE_COMBO_OFFSET
LANGUAGE_X = 550
CURVE_COMBO_X = 250
FORMAT_LABEL_X = 330
SAVE_BUTTON_X = 420
CHECKBOX_X = 450
PREVIEW_X = 800
EDITOR_X = 800
BUTTON_BUILD_X = 1050
SELECT_BUTTON_X = 620
OFFSET_CHECKBOX_X = 150
RANGES_CHECKBOX_X = 410
RANGE_LABEL_X = 500
RANGE_ENTRY_X = 520
RANGE_Y_LABEL_X = 610
RANGE_Y_ENTRY_X = 630
OFFSET_H_LABEL_X = 240
OFFSET_H_ENTRY_X = 270
OFFSET_V_LABEL_X = 320
OFFSET_V_ENTRY_X = 360
LEGEND_TITLE_COMBO_X = 550
LEGEND_TITLE_ENTRY_X = 550

# Вертикальные позиции
CURVE_LABEL_Y = 120
LEGEND_TITLE_Y = 120
CURVES_FRAME_Y = 170
SAVE_FRAME_Y = 300
BUTTON_BUILD_Y = 520
EDITOR_Y = 560
CONTROL_Y = 60
PATH_LABEL_Y = 90
PATH_ENTRY_Y = 110
PATH_LABEL_Y_2 = 140
PATH_ENTRY_Y_2 = 160
LEGEND_LABEL_Y = 150
LEGEND_ENTRY_Y = 170
SELECT_BUTTON_Y = 108
SELECT_BUTTON_Y_2 = 158
SOURCE_LABEL_OFFSET = 30
SOURCE_COMBO_OFFSET = 50
SOURCE_AXIS_LABEL_OFFSET = 75
SOURCE_AXIS_COMBO_OFFSET = 95
ENTRY_CHAR_WIDTH = 10
OFFSET_CHAR_WIDTH = 5

# Высоты блоков
CURVE_HEIGHT = 180
CURVE_HEIGHT_WITH_LEGEND = 210

# Прочее
WRAP_LENGTH = 400

__all__ = [
    "PADDING",
    "LINE_HEIGHT",
    "INPUT_FRAME_WIDTH",
    "INPUT_FRAME_HEIGHT",
    "SAVE_FRAME_WIDTH",
    "SAVE_FRAME_HEIGHT",
    "CURVES_FRAME_WIDTH",
    "CURVES_FRAME_HEIGHT",
    "ENTRY_WIDTH",
    "COMBO_WIDTH",
    "SMALL_COMBO_WIDTH",
    "SIZE_COMBO_WIDTH",
    "FORMAT_COMBO_WIDTH",
    "PATH_ENTRY_WIDTH",
    "RANGE_ENTRY_WIDTH",
    "OFFSET_ENTRY_WIDTH",
    "PREVIEW_WIDTH",
    "PREVIEW_HEIGHT",
    "EDITOR_HEIGHT",
    "AXIS_COMBO_X",
    "AXIS_ENTRY_X",
    "AXIS_LABEL_SIZE_X",
    "AXIS_UNIT_X",
    "LANGUAGE_X",
    "CURVE_COMBO_X",
    "LABEL_SIZE_OFFSET",
    "SIZE_COMBO_OFFSET",
    "FORMAT_LABEL_X",
    "SAVE_BUTTON_X",
    "CHECKBOX_X",
    "PREVIEW_X",
    "EDITOR_X",
    "BUTTON_BUILD_X",
    "SELECT_BUTTON_X",
    "OFFSET_CHECKBOX_X",
    "RANGES_CHECKBOX_X",
    "RANGE_LABEL_X",
    "RANGE_ENTRY_X",
    "RANGE_Y_LABEL_X",
    "RANGE_Y_ENTRY_X",
    "OFFSET_H_LABEL_X",
    "OFFSET_H_ENTRY_X",
    "OFFSET_V_LABEL_X",
    "OFFSET_V_ENTRY_X",
    "LEGEND_TITLE_COMBO_X",
    "LEGEND_TITLE_ENTRY_X",
    "CURVE_LABEL_Y",
    "LEGEND_TITLE_Y",
    "CURVES_FRAME_Y",
    "SAVE_FRAME_Y",
    "BUTTON_BUILD_Y",
    "EDITOR_Y",
    "CONTROL_Y",
    "PATH_LABEL_Y",
    "PATH_ENTRY_Y",
    "PATH_LABEL_Y_2",
    "PATH_ENTRY_Y_2",
    "LEGEND_LABEL_Y",
    "LEGEND_ENTRY_Y",
    "SELECT_BUTTON_Y",
    "SELECT_BUTTON_Y_2",
    "SOURCE_LABEL_OFFSET",
    "SOURCE_COMBO_OFFSET",
    "SOURCE_AXIS_LABEL_OFFSET",
    "SOURCE_AXIS_COMBO_OFFSET",
    "ENTRY_CHAR_WIDTH",
    "OFFSET_CHAR_WIDTH",
    "CURVE_HEIGHT",
    "CURVE_HEIGHT_WITH_LEGEND",
    "WRAP_LENGTH",
]

